### ISSUE TITLE
I hope there will be no line breaks here

### ISSUE THREAD

**Issue by DreUncle** [ringecosystem/msgport-home#10]
![telegram-cloud-photo-size-5-6190413106656689431-y](https://github.com/msgport/home/assets/34929683/fdcc0e16-14aa-4f87-876f-71c792a0fcf7)

**Comment by DreUncle** [comment]
@nblogist Currently this problem still exists under 2560 width

**Comment by nblogist** [comment]
CC @hamidroohi71

**Comment by boundless-forest** [comment]
Done.
