### ISSUE TITLE
Two new modules

### ISSUE THREAD

**Issue by DreUncle** [ringecosystem/msgport-home#11]
![telegram-cloud-photo-size-5-6190413106656689426-y](https://github.com/msgport/home/assets/34929683/3560e487-73e5-4e01-9fda-63e390b9b8b8)
![telegram-cloud-photo-size-5-6190413106656689427-y](https://github.com/msgport/home/assets/34929683/dd2ad38b-7d4f-47c7-95a4-204213c26890)

https://www.figma.com/design/DhNwZFrbuLNoWDUlja9R8O/Darwinia-New-Website?node-id=18184-2559&t=M4nk5wld7cjpcAdi-0
hi, Two new modules have been added to the msgport website, one is the circular scrolling logo, and the other is Resources at the bottom. You can get the links pointed to by Resources on darwinia.network

**Comment by boundless-forest** [comment]
Done. Close it.
