### ISSUE TITLE
The mobile animation needs to be replaced with the mobile-specific animation in the compressed package provided previously.

### ISSUE THREAD

**Issue by DreUncle** [ringecosystem/msgport-home#12]
<img width="448" alt="image" src="https://github.com/msgport/home/assets/34929683/2bb22745-90b0-4cbb-97a4-4ea91d8a7dd2">

[hero-m.mp4.zip](https://github.com/msgport/home/files/15269855/hero-m.mp4.zip)

**Comment by nblogist** [comment]
@hamidroohi71 add a custom hook to listen for dimension changes and then update the branch /fix/#12

**Comment by boundless-forest** [comment]
Would you like to raise a PR and link it to this issue? So others can review and track the status of this issue.
