### ISSUE TITLE
Add `robots.txt` for SEO

### ISSUE THREAD

**Issue by boundless-forest** [ringecosystem/msgport-home#13]
![image](https://github.com/msgport/home/assets/11801722/dd585279-00f6-4ac3-a71b-24321db46607)

Google Search Console shows me this error, I think we need to fix it and make the site easier to index  by the search engines.

**Comment by fewensa** [comment]
We don't need add this anymore, this site is js rendered single web page, robots.txt and sitemap is unnecessary.
For help SEO and social preview  my suggestion is add some more description and meta

reference:
https://blog.bitsrc.io/how-to-generate-previews-for-your-web-page-on-social-media-f867bfd26859

https://socialsharepreview.com
https://metatags.io/
