### ISSUE TITLE
Add social preview card

### ISSUE THREAD

**Issue by fewensa** [ringecosystem/msgport-home#14]
- Add social preview to improve vision and seo. https://metatags.io/
- Add description, tag meta https://ahrefs.com/blog/seo-meta-tags/ https://www.link-assistant.com/news/html-tags-for-seo.html

**Comment by boundless-forest** [comment]
@hamidroohi71  Would you like to pick this up?

**Comment by hamidroohi71** [comment]
Yes, I will pick up this @boundless-forest

**Comment by hamidroohi71** [comment]
CC @nblogist
