### ISSUE TITLE
Some problems with the Resources module

### ISSUE THREAD

**Issue by DreUncle** [ringecosystem/msgport-home#17]
<img width="2455" alt="image" src="https://github.com/msgport/home/assets/34929683/5f4362ca-4409-4e12-a850-b51570bae402">

There needs to be some spacing between the title and the content to make them look separate. Please refer to the design drawing for details.

Also, there are some issues with the width at 2560, I have added references for each resolution
<img width="1563" alt="image" src="https://github.com/msgport/home/assets/34929683/2a1518b9-c098-4e05-a616-4c73a3d87e9b">

**Comment by hamidroohi71** [comment]
@DreUncle Done.

**Comment by boundless-forest** [comment]
Would you like to raise a PR and link it to this issue? So others can review  and track the status of this issue.

**Comment by hamidroohi71** [comment]
PR created
