### ISSUE TITLE
Improve the display of this button

### ISSUE THREAD

**Issue by boundless-forest** [ringecosystem/msgport-home#18]
- link: https://msgport.xyz/

![image](https://github.com/msgport/home/assets/11801722/35364398-14a8-4b4d-bb2e-fdf1c5664fe9)

**Comment by hamidroohi71** [comment]
@boundless-forest this is done. It was done before, but when adding the url, the button has been put in a <a> tag and the style broken. It is fixed now on this branch:  https://github.com/msgport/home/tree/hidotmatrix/fix/%2318

**Comment by boundless-forest** [comment]
Thanks!

**Comment by nblogist** [comment]
Duplicate Issue:  Moved [here](https://github.com/msgport/home/issues/21)
