### ISSUE TITLE
There were some problems with the previous favicon, please try replacing these files. Contains darwinia and msgport

### ISSUE THREAD

**Issue by DreUncle** [ringecosystem/msgport-home#25]
[favicon.zip](https://github.com/msgport/home/files/15345648/favicon.zip)

**Comment by hamidroohi71** [comment]
@DreUncle Ok. Will do it today

**Comment by boundless-forest** [comment]
Would you like to raise a PR and link it to this issue? So others can review and track the status of this issue.

**Comment by hamidroohi71** [comment]
PR created
